<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="VytvorVozidloService"
     targetNamespace="http://xmlns.oracle.com/soa-priklad/soa-autoumyvaren/VytvorVozidloService"
     xmlns:tns="http://xmlns.oracle.com/soa-priklad/soa-autoumyvaren/VytvorVozidloService"
     xmlns:inp1="vozidlo"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="vozidlo" schemaLocation="../Schemas/vozidlo.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="parameters" element="inp1:vytvorVozidloRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="parameters" element="inp1:vytvorVozidloResponse"/>
    </wsdl:message>
    <wsdl:portType name="VytvorVozidloPortType">
        <wsdl:operation name="vytvorVozidlo">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
